name: test Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  databricks-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI and jq
        run: |
          pip install databricks-cli
          sudo apt-get update && sudo apt-get install -y jq
          
      - name: Run Databricks job Train_Register_Model
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks jobs list --output JSON